pollme/pollme/urls.py
from django.contrib import admin
from django.urls import path,include
 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('polls/', include('polls.urls',namespace='polls'))
]

pollme/polls/urls.py
from django.urls import path

from . import views
app_name ="polls"
urlpatterns = [
    path('list/', views.polls_list, name="list")
]

pollme/polls/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    text = models.CharField(max_length=255)
    pub_date =models.DateField()

    def __str__(self):
        return self.text
       

class Choice(models.Model):
    questions = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return "{} . {}".format(self.questions.text[:25], self.choice_text[:25]) # format strings in python each one maps with place holders

pollme/pollme/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request, 'home.html', context)

pollme/polls/views.py
from django.shortcuts import render
from .models import Poll


# Create your views here.
def polls_list(request):
    """
    renders the polls_list.html template which lists all the currently available polls
    """

    polls = Poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/polls_list.html',context)

pollme/polls/templates/polls/polls_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    <h1> welcome to poll list</h1>
    <ul>
    {% for poll  in polls  %}
        <li>{{ poll  }}</li>
    {% endfor %}  
    </ul>
</div>

{% endblock %}

pollme/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <title>Poll Me App</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">

    {% block custom_css %} {% endblock %}
</head>

<body>
    {% include 'includes/navbar.html' %}

    

    {% block content %}
    <h1>welcome !</h1>
    <p> the current datetime is : {{datetime_now }} header changes</p>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>

</body>

</html>

pollme/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
    <link rel='stylesheet' type='text/css' href="{% static 'css/home_style.css'%}">
{% endblock %}
{% block content  %}
<div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content">
                <h1>PollMe -Get started!</h1>
                <h3>Your voice matters!</h3>
                <hr>
                <button type="button" class="btn btn-light btn-lg">Get started!</button>
            </div>
        </div>
    </div>
</div>



{% endblock %}

pollme/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'home'  %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'polls:list' %}">Polls</a>
        </div>
    </div>
</nav>